language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.6

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

services:
  - mysql

before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ez_test;'
  - mysql -e "CREATE USER ez_test@localhost IDENTIFIED BY 'ezTest'; GRANT ALL ON ez_test.* TO ez_test@localhost; FLUSH PRIVILEGES;"

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: 
  - phpunit --coverage-clover=coverage.xml
